apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    app: node
---
apiVersion: v1
kind: Service
metadata:
  name: node-hs
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  clusterIP: None
  selector:
    app: node
